apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-ui
  namespace: demo
  labels:
    app: polling-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polling-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: polling-ui
        ref: <CI_ENV>
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: demo-reg  
      containers:
        - image: registry.citictel.com/demo/polling-ui:<BUILD_TAG>
          imagePullPolicy: IfNotPresent
          name: polling-ui
          ports:
            - containerPort: 80
              name: web
---
kind: Service
apiVersion: v1
metadata:
  name: polling-ui
  namespace: demo
  labels:
    ref: <CI_ENV>
spec:
  selector:
    app: polling-ui
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: web

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: demo
spec:
  rules:
    - host: demo1.citictel.com
      http:
        paths:
          - path: /
            backend:
              serviceName: polling-ui
              servicePort: 80
          - path: /api/
            backend:
              serviceName: polling-server
              servicePort: 8080
